spring:
  application:
    name: ${APP_NAME:FINO}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
    # include: db, jwt
  devtools:
    restart:
      enabled: ${DEVTOOLS_RESTART_ENABLED:false}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/fino_db}
    username: ${SPRING_DATASOURCE_USERNAME:fino_user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: ${SERVLET_ENCODING_CHARSET:UTF-8}
      enabled: ${SERVLET_ENCODING_ENABLED:true}
      force: ${SERVLET_ENCODING_FORCE:true}

springdoc:
  swagger-ui:
    path: ${SWAGGER_UI_PATH:/swagger-ui.html}
    enabled: ${SWAGGER_UI_ENABLED:true}
  api-docs:
    path: ${API_DOCS_PATH:/v3/api-docs}
    enabled: ${API_DOCS_ENABLED:true}
  packages-to-scan: ${PACKAGES_TO_SCAN:com.kangwon.fino}

location:
  auth:
    allowed-distance-meters: ${LOCATION_AUTH_ALLOWED_DISTANCE:150.0}

jwt:
  secret: ${JWT_SECRET:defaultSecretKeyForTestingPurposesOnly}